GET http://localhost:8080/ebook/list?page=1&size=1001

###

POST http://localhost:8080/ebook/save
Content-Type: application/json

{
  "id": 6,
  "name": "C#",
  "docCount": 3,
  "viewCount": 4,
  "voteCount": 5,
  "descption": "一门陌生的语言"
}

###
